scorecard:
  # Setting a global scorecard option
  output: json
  plugins:
    # `basic` tests configured to test 2 CRs
    - basic:
        cr-manifest:
          - "deploy/crds/operator.ibm.com_v1alpha1_certmanager_cr.yaml"
    # `olm` tests configured to test 2 CRs
    - olm:
        cr-manifest:
          - "deploy/crds/operator.ibm.com_v1alpha1_certmanager_cr.yaml"
        csv-path: "deploy/olm-catalog/ibm-cert-manager-operator/3.6.3/ibm-cert-manager-operator.v3.6.3.clusterserviceversion.yaml"
