apiVersion: v1
kind: ServiceAccount
metadata: 
  name: ibm-cert-manager-operator
  namespace: {{ .Values.global.operatorNamespace }}
  labels:
    component-id: {{ .Chart.Name }}
    {{- with .Values.cpfs.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
---
# permissions to do leader election.
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ibm-cert-manager-operator-leader-election-role
  labels:
    app.kubernetes.io/instance: ibm-cert-manager-operator
    app.kubernetes.io/managed-by: ibm-cert-manager-operator
    app.kubernetes.io/name: cert-manager
    component-id: {{ .Chart.Name }}
    {{- with .Values.cpfs.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ibm-cert-manager-operator-leader-election-rolebinding
  labels:
    app.kubernetes.io/instance: ibm-cert-manager-operator
    app.kubernetes.io/managed-by: ibm-cert-manager-operator
    app.kubernetes.io/name: cert-manager
    component-id: {{ .Chart.Name }}
    {{- with .Values.cpfs.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ibm-cert-manager-operator-leader-election-role
subjects:   
- kind: ServiceAccount
  name: ibm-cert-manager-operator
  namespace: {{ .Values.global.operatorNamespace }}
