apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
    operators.operatorframework.io/builder: operator-sdk-v1.24.0
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v3
  name: ibm-cert-manager-api.v1.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
      - kind: Challenge
        name: challenges.acme.cert-manager.io
        version: v1
  description:  |-
    # Ibm Cert Manager API description. 
    The IBM Cert Manager API cannot be installed standalone, it only can be installed by ibm-cert-manager-oeprator by dependency.
  displayName: Ibm Cert Manager API
  icon:
    - base64data: ""
      mediatype: ""
  install:
    spec:
      deployments: []
    strategy: deployment
  installModes:
    - supported: true
      type: OwnNamespace
    - supported: false
      type: SingleNamespace
    - supported: false
      type: MultiNamespace
    - supported: false
      type: AllNamespaces
  keywords:
    - ibm-cert-manager-api
  links:
    - name: Ibm Cert Manager API
      url: https://ibm-cert-manager-operator.domain
  maintainers:
    - email: support@ibm.com
      name: IBM Support
  maturity: alpha
  provider:
    name: IBM
  version: 1.0.0
  relatedImages:
    - image: icr.io/cpopen/ibm-cert-manager-operator:latest
      name: IBM_CERT_MANAGER_OPERATOR_IMAGE