apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/instance: ibm-cert-manager-operator
    app.kubernetes.io/managed-by: ibm-cert-manager-operator
    app.kubernetes.io/name: cert-manager
  name: ibm-cert-manager-operator-leader-election-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ibm-cert-manager-operator-leader-election-role
subjects:
- kind: ServiceAccount
  name: ibm-cert-manager-operator
  namespace: ibm-cert-manager-operator-system
