# permissions for end users to edit challenges.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: challenge-editor-role
rules:
- apiGroups:
  - certmanager.k8s.io
  resources:
  - challenges
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - certmanager.k8s.io
  resources:
  - challenges/status
  verbs:
  - get
