apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: cs-ca-certificate
  labels:
    app.kubernetes.io/instance: ibm-cert-manager-operator
    app.kubernetes.io/managed-by: ibm-cert-manager-operator
    app.kubernetes.io/name: cert-manager
spec:
  issuerRef:
    name: cs-ss-issuer
    kind: Issuer
  secretName: cs-ca-certificate-secret
  isCA: true
  commonName: cs-ca-certificate
