apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: cs-ca-certificate
  namespace: ibm-common-services
spec:
  issuerRef:
    name: cs-ss-issuer
    kind: Issuer
  secretName: cs-ca-certificate-secret
  commonName: cs-ca-certificate
