kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ibm-cert-manager-access
subjects:
- kind: Group
  name: system:serviceaccounts:ibm-common-services
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: ibm-cert-manager-access
  apiGroup: rbac.authorization.k8s.io
