//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CACertificate) DeepCopyInto(out *CACertificate) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CACertificate.
func (in *CACertificate) DeepCopy() *CACertificate {
	if in == nil {
		return nil
	}
	out := new(CACertificate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertManagerConfig) DeepCopyInto(out *CertManagerConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertManagerConfig.
func (in *CertManagerConfig) DeepCopy() *CertManagerConfig {
	if in == nil {
		return nil
	}
	out := new(CertManagerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CertManagerConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertManagerConfigList) DeepCopyInto(out *CertManagerConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CertManagerConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertManagerConfigList.
func (in *CertManagerConfigList) DeepCopy() *CertManagerConfigList {
	if in == nil {
		return nil
	}
	out := new(CertManagerConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CertManagerConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertManagerConfigSpec) DeepCopyInto(out *CertManagerConfigSpec) {
	*out = *in
	if in.DisableHostNetwork != nil {
		in, out := &in.DisableHostNetwork, &out.DisableHostNetwork
		*out = new(bool)
		**out = **in
	}
	in.CertManagerController.DeepCopyInto(&out.CertManagerController)
	in.CertManagerWebhook.DeepCopyInto(&out.CertManagerWebhook)
	in.CertManagerCAInjector.DeepCopyInto(&out.CertManagerCAInjector)
	in.ConfigMapWatcher.DeepCopyInto(&out.ConfigMapWatcher)
	if in.EnableCertRefresh != nil {
		in, out := &in.EnableCertRefresh, &out.EnableCertRefresh
		*out = new(bool)
		**out = **in
	}
	if in.RefreshCertsBasedOnCA != nil {
		in, out := &in.RefreshCertsBasedOnCA, &out.RefreshCertsBasedOnCA
		*out = make([]CACertificate, len(*in))
		copy(*out, *in)
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	out.License = in.License
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertManagerConfigSpec.
func (in *CertManagerConfigSpec) DeepCopy() *CertManagerConfigSpec {
	if in == nil {
		return nil
	}
	out := new(CertManagerConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertManagerConfigStatus) DeepCopyInto(out *CertManagerConfigStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertManagerConfigStatus.
func (in *CertManagerConfigStatus) DeepCopy() *CertManagerConfigStatus {
	if in == nil {
		return nil
	}
	out := new(CertManagerConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertManagerContainerSpec) DeepCopyInto(out *CertManagerContainerSpec) {
	*out = *in
	in.Resources.DeepCopyInto(&out.Resources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertManagerContainerSpec.
func (in *CertManagerContainerSpec) DeepCopy() *CertManagerContainerSpec {
	if in == nil {
		return nil
	}
	out := new(CertManagerContainerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LicenseAcceptance) DeepCopyInto(out *LicenseAcceptance) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LicenseAcceptance.
func (in *LicenseAcceptance) DeepCopy() *LicenseAcceptance {
	if in == nil {
		return nil
	}
	out := new(LicenseAcceptance)
	in.DeepCopyInto(out)
	return out
}
