apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "operator.ibm.com/v1alpha1",
          "kind": "CertManager",
          "metadata": {
            "labels": {
              "app.kubernetes.io/instance": "ibm-cert-manager-operator",
              "app.kubernetes.io/managed-by": "ibm-cert-manager-operator",
              "app.kubernetes.io/name": "cert-manager"
            },
            "name": "default"
          },
          "spec": {
            "disableHostNetwork": true,
            "enableWebhook": true,
            "imageRegistry": "quay.io/opencloudio"
          },
          "status": {
            "certManagerStatus": ""
          }
        },
        {
          "apiVersion": "certmanager.k8s.io/v1alpha1",
          "kind": "Issuer",
          "metadata": {
            "labels": {
              "app.kubernetes.io/instance": "ibm-cert-manager-operator",
              "app.kubernetes.io/managed-by": "ibm-cert-manager-operator",
              "app.kubernetes.io/name": "cert-manager"
            },
            "name": "cs-ss-issuer",
            "namespace": "ibm-common-services"
          },
          "spec": {
            "selfSigned": {}
          }
        },
        {
          "apiVersion": "certmanager.k8s.io/v1alpha1",
          "kind": "Certificate",
          "metadata": {
            "labels": {
              "app.kubernetes.io/instance": "ibm-cert-manager-operator",
              "app.kubernetes.io/managed-by": "ibm-cert-manager-operator",
              "app.kubernetes.io/name": "cert-manager"
            },
            "name": "cs-ca-certificate",
            "namespace": "ibm-common-services"
          },
          "spec": {
            "secretName": "cs-ca-certificate-secret",
            "issuerRef": {
              "name": "cs-ss-issuer",
              "kind": "Issuer"
            },
            "commonName": "cs-ca-certificate",
            "isCA": true
          }
        },
        {
          "apiVersion": "certmanager.k8s.io/v1alpha1",
          "kind": "ClusterIssuer",
          "metadata": {
            "labels": {
              "app.kubernetes.io/instance": "ibm-cert-manager-operator",
              "app.kubernetes.io/managed-by": "ibm-cert-manager-operator",
              "app.kubernetes.io/name": "cert-manager"
            },
            "name": "cs-ca-clusterissuer"
          },
          "spec": {
            "ca": {
              "secretName": "cs-ca-certificate-secret"
            }
          }
        }
      ]
    capabilities: Basic Install
    categories: Security
    certified: "false"
    containerImage: quay.io/opencloudio/ibm-cert-manager-operator:latest
    createdAt: "2020-04-10T10:16:16Z"
    description: Operator for managing deployment of cert-manager service.
    support: IBM
  name: ibm-cert-manager-operator.v3.6.0
  namespace: ibm-common-services
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: Represents a certificate
      displayName: Certificate
      kind: Certificate
      name: certificates.certmanager.k8s.io
      version: v1alpha1
    - description: Represents a cluster issuer
      displayName: Cluster Issuer
      kind: ClusterIssuer
      name: clusterissuers.certmanager.k8s.io
      version: v1alpha1
    - description: Represents an issuer
      displayName: Issuer
      kind: Issuer
      name: issuers.certmanager.k8s.io
      version: v1alpha1
    - description: CertManager is the Schema for the certmanagers API
      kind: CertManager
      name: certmanagers.operator.ibm.com
      statusDescriptors:
      - description: It will be as "OK when all objects are created successfully
        displayName: CertManager Status
        path: certManagerStatus
        x-descriptors:
        - 'urn:alm:descriptor:com.tectonic.ui:podStatuses'
      version: v1alpha1
      displayName: CertManager
      resources:
      - kind: Deployment
        name: ''
        version: v1
      - kind: ClusterRole
        name: clusterroles.rbac.authorization.k8s.io
        version: v1
      - kind: ClusterRoleBinding
        name: clusterrolebindings.rbac.authorization.k8s.io
        version: v1
      - kind: CustomResourceDefinition
        name: customresourcedefinitions.apiextensions.k8s.io
        version: v1beta1
      - kind: ServiceAccount
        name: ''
        version: v1
      - kind: ValidatingWebhookConfiguration
        name: validatingwebhookconfigurations.admissionregistration.k8s.io
        version: v1beta1
      - kind: MutatingWebhookConfiguration
        name: mutatingwebhookconfigurations.admissionregistration.k8s.io
        version: v1beta1
      - kind: Service
        name: ''
        version: v1
      - kind: APIService
        name: apiservices.apiregistration.k8s.io
        version: v1
      specDescriptors:
      - description: Disables the use of hostNetwork by the webhook
        displayName: DisableHostNetwork
        path: disableHostNetwork
        x-descriptors:
        - 'urn:alm:descriptor:com.tectonic.ui:text'
      - description: Enables the webhook component of cert-manager when set to true
        displayName: EnableWebhook
        path: enableWebhook
        x-descriptors:
        - 'urn:alm:descriptor:com.tectonic.ui:text'
      - description: Appends the text to the image tag when it deploys cert-manager
        displayName: ImagePostFix
        path: imagePostFix
        x-descriptors:
        - 'urn:alm:descriptor:com.tectonic.ui:text'
      - description: Sets the image registry to this when deploying cert-manager
        displayName: ImageRegistry
        path: imageRegistry
        x-descriptors:
        - 'urn:alm:descriptor:com.tectonic.ui:text'
      - description: The namespace where namespace scoped resources referenced by cert-manager clusterissuers must be placed
        displayName: ResourceNamespace
        path: resourceNamespace
        x-descriptors:
        - 'urn:alm:descriptor:com.tectonic.ui:text'
  description: Operator for managing deployment of cert-manager service.
  displayName: Ibm Cert Manager Operator
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - operator.ibm.com
          resources:
          - certmanagers
          verbs:
          - '*'
        - apiGroups:
          - ""
          resources:
          - pods
          - services
          - services/finalizers
          - endpoints
          - persistentvolumeclaims
          - events
          - configmaps
          - secrets
          - serviceaccounts
          - namespaces
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - apps
          resources:
          - deployments
          - daemonsets
          - replicasets
          - statefulsets
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - servicemonitors
          verbs:
          - get
          - create
        - apiGroups:
          - apps
          resourceNames:
          - cert-manager-operator
          resources:
          - deployments/finalizers
          verbs:
          - update
        - apiGroups:
          - apps
          resources:
          - replicasets
          - deployments
          verbs:
          - get
        - apiGroups:
          - operator.ibm.com
          resources:
          - '*'
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - apiextensions.k8s.io
          resources:
          - customresourcedefinitions
          verbs:
          - '*'
        - apiGroups:
          - rbac.authorization.k8s.io
          resources:
          - clusterroles
          - clusterrolebindings
          - roles
          - rolebindings
          verbs:
          - create
          - get
          - list
          - watch
          - patch
          - update
          - delete
        - apiGroups:
          - apiregistration.k8s.io
          resources:
          - apiservices
          verbs:
          - create
          - get
          - list
          - watch
          - patch
          - update
          - delete
        - apiGroups:
          - admissionregistration.k8s.io
          resources:
          - mutatingwebhookconfigurations
          - validatingwebhookconfigurations
          verbs:
          - create
          - get
          - list
          - watch
          - patch
          - update
          - delete
        - apiGroups:
          - certmanager.k8s.io
          resources:
          - certificates
          - certificaterequests
          - orders
          - challenges
          - clusterissuers
          - issuers
          verbs:
          - '*'
        - apiGroups:
          - certmanager.k8s.io
          resources:
          - certificates/status
          - certificaterequests/status
          - challenges/status
          - orders/status
          - issuers/status
          - clusterissuers/status
          - certificates/finalizers
          - challenges/finalizers
          - ingresses/finalizers
          - orders/finalizers
          verbs:
          - update
        - apiGroups:
          - ""
          resources:
          - secrets
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - delete
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        - apiGroups:
          - ""
          resources:
          - pods
          - services
          verbs:
          - get
          - list
          - watch
          - create
          - delete
        - apiGroups:
          - extensions
          resources:
          - ingresses
          verbs:
          - get
          - list
          - watch
          - create
          - delete
          - update
        - apiGroups:
          - apps
          resources:
          - deployments
          - statefulsets
          - daemonsets
          verbs:
          - '*'
        - apiGroups:
          - route.openshift.io
          resources:
          - routes/custom-host
          verbs:
          - create
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - create
          - update
          - patch
        - apiGroups:
          - admission.certmanager.k8s.io
          resources:
          - certificates
          - clusterissuers
          - issuers
          - certificaterequests
          verbs:
          - '*'
        - apiGroups:
          - security.openshift.io
          resourceNames:
          - restricted
          - hostnetwork
          resources:
          - securitycontextconstraints
          verbs:
          - use
        - apiGroups:
          - admissionregistration.k8s.io
          resources:
          - mutatingwebhookconfigurations
          - validatingwebhookconfigurations
          verbs:
          - '*'
        - apiGroups:
          - apiregistration.k8s.io
          resources:
          - apiservices
          verbs:
          - '*'
        - apiGroups:
          - authorization.k8s.io
          resources:
          - subjectaccessreviews
          verbs:
          - '*'
        - apiGroups:
          - operators.open-cluster-management.io
          resources:
          - multiclusterhubs
          verbs:
          - get
          - list
          - watch
        serviceAccountName: ibm-cert-manager-operator
      deployments:
      - name: ibm-cert-manager-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: ibm-cert-manager-operator
          strategy: {}
          template:
            metadata:
              annotations:
                productName: IBM Cloud Platform Common Services
                productID: 068a62892a1e4db39641342e592daa25
                productVersion: "3.4.0"
                productMetric: FREE
              labels:
                app.kubernetes.io/instance: ibm-cert-manager-operator
                app.kubernetes.io/managed-by: ibm-cert-manager-operator
                app.kubernetes.io/name: cert-manager
                name: ibm-cert-manager-operator
            spec:
              affinity:
                nodeAffinity:
                  requiredDuringSchedulingIgnoredDuringExecution:
                    nodeSelectorTerms:
                    - matchExpressions:
                      - key: beta.kubernetes.io/arch
                        operator: In
                        values:
                        - amd64
                        - ppc64le
                        - s390x
              containers:
              - args:
                - --zap-level=1
                command:
                - ibm-cert-manager-operator
                env:
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.annotations['olm.targetNamespaces']
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: OPERATOR_NAME
                  value: ibm-cert-manager-operator
                image: quay.io/opencloudio/ibm-cert-manager-operator:latest
                imagePullPolicy: Always
                name: ibm-cert-manager-operator
                resources:
                  limits:
                    cpu: 20m
                    memory: 90Mi
                  requests:
                    cpu: 10m
                    memory: 50Mi
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
                  privileged: false
                  readOnlyRootFilesystem: true
              serviceAccountName: ibm-cert-manager-operator
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - Cert-Manager
  - IBM
  - Cloud
  maintainers:
  - email: swati.nair@ibm.com
    name: Swati Shridhar Nair
  - email: tthorpe@us.ibm.com
    name: Robert T. Thorpe
  maturity: alpha
  provider:
    name: IBM
  replaces: ibm-cert-manager-operator.v3.5.0
  version: 3.6.0
